project:
  type: website
  output-dir: docs

website:
  title: "R_medicine_competition_MGM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: FALSE
    code-tools:
      source: TRUE
      toggle: TRUE
      caption: none

editor: visual


