project:
  type: website
  
website:
  title: "R_medicine_competition_MGM"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: lux
    css: styles.css
    toc: TRUE
    code-fold: TRUE
    code-summary: "Show the code"
    embed-resources: FALSE
    code-tools:
      source: TRUE
      toggle: TRUE
      caption: none
editor: visual